### ISSUE TITLE
error please install tkinter

### ISSUE THREAD

**Issue by elfelround** [dgarciac/toggle_hosts#1]
Traceback (most recent call last):
  File "/home/erick-gasulla/toggle_hosts/toggle_hosts.py", line 4, in <module>
    from tkinter import *
  File "/usr/lib/python3.5/tkinter/__init__.py", line 38, in <module>
    raise ImportError(str(msg) + ', please install the python3-tk package')
ImportError: No module named '_tkinter', please install the python3-tk package

**Comment by ghost** [comment]
Try this maybe it should help 
go cmd(if you are on windows) -> type:
pip install tkinter. 

but I am really new here and I think you did not install tkinter lib and tried to call them.

I hope it will help.

**Comment by elfelround** [comment]
Yes it was a matter of python3-tk dependency, i actually opened the issue just to inform but it was easily solved

i also found on the install.sh this to work better

dpkg -s python3-tk 2>/dev/null >/dev/null || sudo apt-get -y install python3-tk

however a workmate has some sort of issue probably related to her computer routes
